In [1]:
import pandas as pd
import numpy as np
from sklearn.multiclass import OneVsRestClassifier
from sklearn.svm import LinearSVC
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score


In [2]:
df_settlement = pd.read_excel("C:\\Users\\psamp\\AnacondaProjects\\AsbestosIndemnity3.xlsx") 

In [3]:
df_settlement

diseasecategory                                       Jurisdiction  \
0         LUNG CANCER                                            West-PA   
1       NON-MALIGNANT                              Pennsylvania - ALL-PA   
2         LUNG CANCER                                  New York - ALL-NY   
3       NON-MALIGNANT                                            West-PA   
4        MESOTHELIOMA                                  Illinois - ALL-IL   
5         LUNG CANCER                                  New York - ALL-NY   
6       NON-MALIGNANT                                  Madison County-IL   
7        MESOTHELIOMA                                  Madison County-IL   
8        MESOTHELIOMA                                  Madison County-IL   
9         LUNG CANCER                                           Other-NY   
10        LUNG CANCER                                  Madison County-IL   
11        LUNG CANCER                                            West-PA   
12        LUNG CANCER                                  New York - ALL-NY   
13       MESOTHELIOMA              Northern (San Francisco and north)-CA   
14      NON-MALIGNANT              Northern (San Francisco and north)-CA   
15      NON-MALIGNANT                                California - ALL-CA   
16      NON-MALIGNANT              Northern (San Francisco and north)-CA   
17        LUNG CANCER                                  New York - ALL-NY   
18       MESOTHELIOMA                                           Other-NY   
19       OTHER CANCER              Northern (San Francisco and north)-CA   
20        LUNG CANCER                                           Other-NY   
21      NON-MALIGNANT                                           Other-NY   
22      NON-MALIGNANT                                           Other-NY   
23      NON-MALIGNANT                Southern (Los Angeles and south)-CA   
24       OTHER CANCER                                     Cook County-IL   
25        LUNG CANCER              Northern (San Francisco and north)-CA   
26      NON-MALIGNANT              Northern (San Francisco and north)-CA   
27        LUNG CANCER  Central (north of Los Angeles; south of San Fr...   
28       MESOTHELIOMA              Northern (San Francisco and north)-CA   
29      NON-MALIGNANT              Northern (San Francisco and north)-CA   
...               ...                                                ...   
86528   NON-MALIGNANT                                California - ALL-CA   
86529     LUNG CANCER                                  Madison County-IL   
86530   NON-MALIGNANT              Northern (San Francisco and north)-CA   
86531    MESOTHELIOMA                                            East-PA   
86532    MESOTHELIOMA              Northern (San Francisco and north)-CA   
86533    MESOTHELIOMA                                     Cook County-IL   
86534    MESOTHELIOMA                                California - ALL-CA   
86535    MESOTHELIOMA                                  New York - ALL-NY   
86536    MESOTHELIOMA                                  Madison County-IL   
86537     LUNG CANCER                                  New York - ALL-NY   
86538    MESOTHELIOMA                                  Madison County-IL   
86539     LUNG CANCER                                     Cook County-IL   
86540   NON-MALIGNANT              Northern (San Francisco and north)-CA   
86541     LUNG CANCER                                           Other-NY   
86542    MESOTHELIOMA                                           Other-NY   
86543    MESOTHELIOMA              Northern (San Francisco and north)-CA   
86544    MESOTHELIOMA                                     Cook County-IL   
86545   NON-MALIGNANT                                     Cook County-IL   
86546    MESOTHELIOMA                                     Cook County-IL   
86547     LUNG CANCER                                     Cook County-IL   
86548   NON-MALIGNANT              Northern (San Franc

In [4]:
df_hotcodingdisease = pd.get_dummies(df_settlement['diseasecategory'])

In [5]:
df_hotcodingjurisdiction = pd.get_dummies(df_settlement['Jurisdiction'])

In [6]:
df_final = pd.concat([df_settlement,df_hotcodingdisease,df_hotcodingjurisdiction], axis = 1)


In [7]:
df_final = df_final.drop(['diseasecategory','Jurisdiction'],axis=1)

In [8]:
df_final = df_final.drop(['indemnitypaid'],axis=1)

In [9]:
df_final

Indemnity_Paid_Bin  LUNG CANCER  MESOTHELIOMA  NON-MALIGNANT  \
0                       1            1             0              0   
1                       1            0             0              1   
2                       2            1             0              0   
3                       1            0             0              1   
4                       3            0             1              0   
5                       1            1             0              0   
6                       1            0             0              1   
7                       2            0             1              0   
8                       4            0             1              0   
9                       2            1             0              0   
10                      1            1             0              0   
11                      1            1             0              0   
12                      2            1             0              0   
13                      2            0             1              0   
14                      1            0             0              1   
15                      1            0             0              1   
16                      1            0             0              1   
17                      2            1             0              0   
18                      2            0             1              0   
19                      1            0             0              0   
20                      1            1             0              0   
21                      1            0             0              1   
22                      1            0             0              1   
23                      1            0             0              1   
24                      1            0             0              0   
25                      1            1             0              0   
26                      1            0             0              1   
27                      1            1             0              0   
28                      1            0             1              0   
29                      1            0             0              1   
...                   ...          ...           ...            ...   
86528                   1            0             0              1   
86529                   2            1             0              0   
86530                   1            0             0              1   
86531                   1            0             1              0   
86532                   1            0             1              0   
86533                   3            0             1              0   
86534                   1            0             1              0   
86535                   3            0             1              0   
86536                   3            0             1              0   
86537                   2            1             0              0   
86538                   1            0             1              0   
86539                   1            1             0              0   
86540                   1            0             0              1   
86541                   2            1             0              0   
86542                   4            0             1              0   
86543                   2            0             1              0   
86544                   1            0             1              0   
86545                   1            0             0              1   
86546                   3            0             1              0   
86547                   1            1             0              0   
86548                   1            0             0              1   
86549                   1            0             0              1   
86550                   2            1             0              0   
86551                   2            0             1              0   
86552                   1      

In [10]:
X = df_final.drop(['Indemnity_Paid_Bin'], axis = 1)
y = df_final.Indemnity_Paid_Bin

X = X.values
y = y.values


In [11]:
X_train , X_test , y_train , y_test = train_test_split(X,y,test_size=0.25,random_state=1 )


In [12]:
y_train

array([1, 1, 1, ..., 1, 1, 1], dtype=int64)

In [13]:
clf = OneVsRestClassifier(LinearSVC(random_state=0)).fit(X_train, y_train)

In [14]:
y_pred = clf.predict(X_test)

In [18]:
accuracy_score(y_test, y_pred)

0.70480591497227352

In [16]:
y_pred

array([1, 1, 1, ..., 1, 1, 1], dtype=int64)

In [17]:
y_test

array([1, 1, 1, ..., 1, 1, 5], dtype=int64)