In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler
from sklearn.pipeline import Pipeline
from sklearn.model_selection import train_test_split


In [2]:
df_settlement = pd.read_excel("C:\\Users\\psamp\\AnacondaProjects\\AsbestosIndemnity.xlsx") 

In [3]:
df_settlement

indemnitypaid diseasecategory                           Jurisdiction
0             7500.0   NON-MALIGNANT  Northern (San Francisco and north)-CA
1           235000.0    MESOTHELIOMA                               Other-NY
2            12500.0   NON-MALIGNANT  Northern (San Francisco and north)-CA
3             7500.0   NON-MALIGNANT  Northern (San Francisco and north)-CA
4            25000.0     LUNG CANCER                               Other-NY
5            75000.0    MESOTHELIOMA                               Other-NY
6           125000.0     LUNG CANCER                               Other-NY
7             7500.0   NON-MALIGNANT  Northern (San Francisco and north)-CA
8             6500.0    MESOTHELIOMA                      Madison County-IL
9            20000.0     LUNG CANCER                               Other-NY
10           40000.0    MESOTHELIOMA                      New York - ALL-NY
11           25000.0    MESOTHELIOMA                      Madison County-IL
12           10000.0    MESOTHELIOMA                                East-PA
13           15000.0   NON-MALIGNANT                    California - ALL-CA
14           75000.0    MESOTHELIOMA                      Madison County-IL
15           50000.0    MESOTHELIOMA                               Other-NY
16           20000.0    MESOTHELIOMA                      Madison County-IL
17            6500.0    MESOTHELIOMA                      Madison County-IL
18           20000.0    MESOTHELIOMA                      Madison County-IL
19            6500.0    MESOTHELIOMA                      Madison County-IL
20           12500.0   NON-MALIGNANT    Southern (Los Angeles and south)-CA
21            6500.0    MESOTHELIOMA                      Madison County-IL
22           25000.0    MESOTHELIOMA                      Madison County-IL
23            7500.0    MESOTHELIOMA                      Madison County-IL
24          150000.0    MESOTHELIOMA                      Madison County-IL
25          131500.0    MESOTHELIOMA                      Madison County-IL
26           35000.0    MESOTHELIOMA                      Madison County-IL
27           30000.0    MESOTHELIOMA                      Madison County-IL
28          100000.0    MESOTHELIOMA                      Madison County-IL
29          100000.0    MESOTHELIOMA                      Madison County-IL
...              ...             ...                                    ...
87435          675.0   NON-MALIGNANT                    California - ALL-CA
87436         5000.0   NON-MALIGNANT                    California - ALL-CA
87437          164.0   NON-MALIGNANT                                West-PA
87438       400000.0    MESOTHELIOMA    Southern (Los Angeles and south)-CA
87439         3750.0   NON-MALIGNANT                    California - ALL-CA
87440          700.0   NON-MALIGNANT                    California - ALL-CA
87441         1500.0     LUNG CANCER                         Cook County-IL
87442        20000.0    MESOTHELIOMA    Southern (Los Angeles and south)-CA
87443         5000.0     LUNG CANCER                                East-PA
87444          150.0   NON-MALIGNANT                                West-PA
87445         1500.0   NON-MALIGNANT                    California - ALL-CA
87446          181.0     LUNG CANCER                                West-PA
87447          900.0   NON-MALIGNANT                    California - ALL-CA
87448        35000.0    MESOTHELIOMA                    California - ALL-CA
87449          900.0   NON-MALIGNANT                                West-PA
87450          600.0   NON-MALIGNANT                                West-PA
87451          500.0    MESOTHELIOMA                                West-PA
87452          600.0   NON-MALIGNANT                  Pennsylvania - ALL-PA
87453         1500.0   NON-MALIGNANT                    California - ALL-CA
87454          900.0   NON-MALIGNANT                                West-PA
87455        12500.0     LUNG CANCER                   

In [4]:
df_hotcodingdisease = pd.get_dummies(df_settlement['diseasecategory'])

In [5]:
df_hotcodingjurisdiction = pd.get_dummies(df_settlement['Jurisdiction'])

In [6]:
df_final = pd.concat([df_settlement,df_hotcodingdisease,df_hotcodingjurisdiction], axis = 1)


In [7]:
df_final = df_final.drop(['diseasecategory','Jurisdiction'],axis=1)

In [8]:
df_final

indemnitypaid  LUNG CANCER  MESOTHELIOMA  NON-MALIGNANT  OTHER CANCER  \
0             7500.0            0             0              1             0   
1           235000.0            0             1              0             0   
2            12500.0            0             0              1             0   
3             7500.0            0             0              1             0   
4            25000.0            1             0              0             0   
5            75000.0            0             1              0             0   
6           125000.0            1             0              0             0   
7             7500.0            0             0              1             0   
8             6500.0            0             1              0             0   
9            20000.0            1             0              0             0   
10           40000.0            0             1              0             0   
11           25000.0            0             1              0             0   
12           10000.0            0             1              0             0   
13           15000.0            0             0              1             0   
14           75000.0            0             1              0             0   
15           50000.0            0             1              0             0   
16           20000.0            0             1              0             0   
17            6500.0            0             1              0             0   
18           20000.0            0             1              0             0   
19            6500.0            0             1              0             0   
20           12500.0            0             0              1             0   
21            6500.0            0             1              0             0   
22           25000.0            0             1              0             0   
23            7500.0            0             1              0             0   
24          150000.0            0             1              0             0   
25          131500.0            0             1              0             0   
26           35000.0            0             1              0             0   
27           30000.0            0             1              0             0   
28          100000.0            0             1              0             0   
29          100000.0            0             1              0             0   
...              ...          ...           ...            ...           ...   
87435          675.0            0             0              1             0   
87436         5000.0            0             0              1             0   
87437          164.0            0             0              1             0   
87438       400000.0            0             1              0             0   
87439         3750.0            0             0              1             0   
87440          700.0            0             0              1             0   
87441         1500.0            1             0              0             0   
87442        20000.0            0             1              0             0   
87443         5000.0            1             0              0             0   
87444          150.0            0             0              1             0   
87445         1500.0            0             0              1             0   
87446          181.0            1             0              0             0   
87447          900.0            0             0              1             0   
87448        35000.0            0             1              0             0   
87449          900.0            0             0              1             0   
87450          600.0            0             0              1             0   
87451          500.0            0             1              0             0   
87452          600.0            0             0              1             0   
87453  

In [9]:
X = df_final.drop(['indemnitypaid'],axis=1)
y = df_final.indemnitypaid

In [10]:
X = X.values
y = y.values

In [11]:
X_train , X_test , y_train , y_test = train_test_split(X,y,test_size=0.25,random_state=1 )

In [12]:
from sklearn import linear_model

clf = linear_model.SGDRegressor()
clf.fit(X_train, y_train)

C:\prashanth\anaconda\lib\site-packages\sklearn\linear_model\stochastic_gradient.py:128: FutureWarning: max_iter and tol parameters have been added in <class 'sklearn.linear_model.stochastic_gradient.SGDRegressor'> in 0.19. If both are left unset, they default to max_iter=5 and tol=None. If tol is not None, max_iter defaults to max_iter=1000. From 0.21, default max_iter will be 1000, and default tol will be 1e-3.
  "and default tol will be 1e-3." % type(self), FutureWarning)


SGDRegressor(alpha=0.0001, average=False, epsilon=0.1, eta0=0.01,
       fit_intercept=True, l1_ratio=0.15, learning_rate='invscaling',
       loss='squared_loss', max_iter=None, n_iter=None, penalty='l2',
       power_t=0.25, random_state=None, shuffle=True, tol=None, verbose=0,
       warm_start=False)

In [13]:
predicted = clf.predict(X_test)

In [14]:
predicted

array([  1.71950285e+04,  -7.61064893e+01,   9.70313689e+03, ...,
         1.56022554e+04,  -1.96757997e+04,   8.91900888e+04])

In [15]:
predicted.astype(int)

array([ 17195,    -76,   9703, ...,  15602, -19675,  89190])

In [12]:
from sklearn import svm

In [13]:
clf = svm.SVR()

In [14]:
clf.fit(X_train, y_train)

SVR(C=1.0, cache_size=200, coef0=0.0, degree=3, epsilon=0.1, gamma='auto',
  kernel='rbf', max_iter=-1, shrinking=True, tol=0.001, verbose=False)

In [15]:
predicted = clf.predict(X_test)

In [16]:
predicted.astype(int)

array([ 7883,  7635,  7477, ..., 10000,  7804, 11984])

In [25]:
predicted.shape


(21867,)

In [30]:
y


array([   7500.,  235000.,   12500., ...,     900.,     900.,     900.])

In [31]:
from sklearn import metrics
metrics.mean_squared_error(y_test,predicted)

20125064531.521599